name = "devawesome"
license = "MIT"
description = "A minimalist, responsive theme inspired by terminal ricing aesthetics."


tags = ["responsive", "minimal", "dark mode"]
features = []

[author]
  name = "Joe Roe"
  homepage = "https://joeroe.io"

